<?php
define("WEB_FOLDER", $_SERVER["HTTP_HOST"]);
define ("CSS_FOLDER", "/css");
define("ROOT_FOLDER", __DIR__);
define("PATTERN_FOLDER", ROOT_FOLDER . DIRECTORY_SEPARATOR . "pages" . DIRECTORY_SEPARATOR . "paterns");
define("HEAD_FILE", PATTERN_FOLDER . DIRECTORY_SEPARATOR . "Head.php");
define("FOOT_FILE", PATTERN_FOLDER . DIRECTORY_SEPARATOR . "Foot.php");
